### PR TITLE
Install instructions for M1 (Pro)

### PR DESCRIPTION
**Pull request by Baschdl**
This installation process works for me. Maybe we can find a cleaner way?

### CODE REVIEW

**Comment by Baschdl** [comment]
I can install it that way but importing `cytopath` throws an error:
```python
>>> import cytopath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sebastian/miniconda3/lib/python3.8/site-packages/cytopath/__init__.py", line 1, in <module>
    from . import anndata
  File "/Users/sebastian/miniconda3/lib/python3.8/site-packages/cytopath/anndata.py", line 1, in <module>
    from anndata import *
  File "/Users/sebastian/miniconda3/lib/python3.8/site-packages/anndata/__init__.py", line 7, in <module>
    from ._core.anndata import AnnData, ImplicitModificationWarning
  File "/Users/sebastian/miniconda3/lib/python3.8/site-packages/anndata/_core/anndata.py", line 17, in <module>
    import h5py
  File "/Users/sebastian/miniconda3/lib/python3.8/site-packages/h5py/__init__.py", line 56, in <module>
    from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z, h5pl
ImportError: dlopen(/Users/sebastian/miniconda3/lib/python3.8/site-packages/h5py/h5fd.cpython-38-darwin.so, 0x0002): Symbol not found: _H5FD_ros3_init
  Referenced from: /Users/sebastian/miniconda3/lib/python3.8/site-packages/h5py/h5fd.cpython-38-darwin.so
  Expected in: /opt/homebrew/Cellar/hdf5/1.12.1/lib/libhdf5.200.dylib
```

Do we need hdf5 in every case?

**Comment by aron0093** [comment]
hdf5 is a dependancy for anndata so I highly doubt it can be skipped. There appears to be a noarch version but I couldn't locate the updated package mentioned in this issue: [#theislab/anndata#592](https://github.com/theislab/anndata/issues/592#issuecomment-964254121)

**Comment by Baschdl** [comment]
I think they talk about [https://anaconda.org/conda-forge/anndata](https://anaconda.org/conda-forge/anndata).  `noarch` is still at v0.6.22.post1 but `osx-arm64` is at v0.7.8 so I would assume that this works. I never added a package to conda myself but wouldn't you need to add `cytopath` to conda such that we could use the dependencies from there?

**Comment by aron0093** [comment]
An interim solution would be to first install anndata using conda (see below) and then installing cytopath. Can you try this?

`conda install -c https://conda.anaconda.org/conda-forge/osx-arm64/ anndata`

**Pull request closed without merging**
